### ISSUE TITLE
第二题给出的手机入参问题

### ISSUE THREAD

**Issue by Helen-Shen** [alaahong/open_automation_quiz#4]
第二题从整个用例来看应该是一个成功的执行用例，而在第二页操作输入中给出的需要填写的手机号少了一位，是不能正确通过格式校验进入下一页的。

**Comment by alaahong** [comment]
> 第二题从整个用例来看应该是一个成功的执行用例，而在第二页操作输入中给出的需要填写的手机号少了一位，是不能正确通过格式校验进入下一页的。

理解正确，请按照happy follow修改数据执行。
