### ISSUE TITLE
项目链接

### ISSUE THREAD

**Issue by Helen-Shen** [alaahong/open_automation_quiz#5]
testng封装：https://github.com/Helen-Shen/zd-testng-core
selenium封装：https://github.com/Helen-Shen/zd-selenium-core
第一题：https://github.com/Helen-Shen/zd-question-selenium
第二题：https://github.com/Helen-Shen/zd-question-cucumber
第三题：https://github.com/Helen-Shen/zd-question-appium

备注：
1、三题中对testng和selenium由通用性，所以进行封装拆分，要运行需要下载testng封装和selenium并进行mvn install
2、第二题中描述截图第二页和点击跳转下一页顺序有冲突，题目中描述的是先点击跳转到下一页然后再截图第二页，顺序有问题，实现是基于先截图第二页再点击跳转下一页进行的。
3、环境详见项目README.md

**Comment by alaahong** [comment]
Thanks, will check detail tomorrow.
Seems no need to split as several projects...
