### ISSUE TITLE
ruihan's test

### ISSUE THREAD

**Issue by RuiHanz** [alaahong/open_automation_quiz#7]
Please check the code
https://github.com/RuiHanz/open_automation_quiz.git
Thanks.

**Comment by RuiHanz** [comment]
Please check the code

**Comment by alaahong** [comment]
Thanks for your commit. But seems build failed, can you check to pass the CI? 
https://github.com/RuiHanz/open_automation_quiz/runs/6858878382?check_suite_focus=true

**Comment by alaahong** [comment]
BTW, the submit code should be not executable as incorrect path, so we can't run your code directly via mvn test.  I guess you might manually import all jars in IDE, that's a bad practice in enterprise project. 
Please try to verify your code as the way mentioned in README. 
`mvn test`

**Comment by alaahong** [comment]
Closed by candidate gave up.
