### ISSUE TITLE
test done

### ISSUE THREAD

**Issue by LianShiyu** [alaahong/open_automation_quiz#8]
https://github.com/LianShiyu/open_automation_quiz.git

**Comment by alaahong** [comment]
@LianShiyu  thanks for your commit. Just trigger the github actions for validation, seems build failed, can you try to fix? --> https://github.com/LianShiyu/open_automation_quiz/runs/6873695137?check_suite_focus=true

BTW, which vendor refer you for this quiz? I didn't received any CV including your name.  Please contact us if you're interested this position, the relative HC is still opening at this moment.

**Comment by alaahong** [comment]
Close by no further response from Candidate here.
